# Gmail
mail.smtp.host=smtp.gmail.com
mail.smtp.port=587
mail.smtp.auth=true
mail.smtp.starttls.enable=true
mail.smtp.ssl.protocols=TLSv1.2
mail.smtp.username=douglas.bocatto@gmail.com
mail.smtp.password= Assombrado_01
mail.smtp.from.name=nexacore


# Este é um arquivo de configuração para as propriedades de e-mail da aplicação.
# Outlook/Microsoft 365.
mail.smtp.host=smtp.office365.com
mail.smtp.port=587
mail.smtp.auth=true
mail.smtp.starttls.enable=true
mail.smtp.ssl.protocols=TLSv1.2
mail.smtp.username=douglas.bocatto@cbadiesel.com.br
mail.smtp.password=Assombrado@01
mail.smtp.from.name=nexacore